name: "Create artifacts"

on: "workflow_dispatch"

jobs:
  build:
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
        os: ["linux", "darwin", "windows"]
    timeout-minutes: 15
    name: "Create artifacts"
    runs-on: "ubuntu-latest"

    steps:
      - name: Create .env
        run: |
          echo 'export GOARCH=${{ matrix.arch }}' > .env
          echo 'export GOOS=${{ matrix.os }}' >> .env

      - uses: "actions/checkout@v7"
      - uses: "actions/setup-go@v7"
        with:
          go-version: "1.26"
          cache-dependency-path: |
            go.sum
            .env

      - run: "make build"
      - uses: "actions/upload-artifact@v7"
        with:
          name: "welp-${{ matrix.os }}-${{ matrix.arch }}"
          path: "out/welp"
